module.exports = {
    queues: {
        TRANSCRIBE_VIDEO_QUEUE: 'TRANSCRIBE_VIDEO_QUEUE',
        TRANSCRIBE_VIDEO_STARTED_QUEUE: 'TRANSCRIBE_VIDEO_STARTED_QUEUE',
        TRANSCRIBE_FINISH_QUEUE: 'TRANSCRIBE_FINISH_QUEUE',
        TRANSCRIBE_VIDEO_FAILED_QUEUE: 'TRANSCRIBE_VIDEO_FAILED_QUEUE',
        TRANSCRIBE_VIDEO_FINISHED_QUEUE: 'TRANSCRIBE_VIDEO_FINISHED_QUEUE',
        TRANSCRIBE_SUBVIDEOS_QUEUE: 'TRANSCRIBE_SUBVIDEOS_QUEUE',

        CONVERT_VIDEO_TO_ARTICLE_QUEUE: 'CONVERT_VIDEO_TO_ARTICLE_QUEUE',
        EXPORT_ARTICLE_TRANSLATION: `EXPORT_ARTICLE_TRANSLATION`,
        EXPORT_ARTICLE_TRANSLATION_FINISH: `EXPORT_ARTICLE_TRANSLATION_FINISH`,
        VIDEO_PROOFREADING_READY: 'VIDEO_PROOFREADING_READY',
    },
    TRANSCRIPTIONSCRIPTS_DIRECTORY: 'transcription_scripts'
}