FROM hassanamin994/node_ffmpeg

WORKDIR /transcriber-service

RUN echo ${GOOGLE_CLOUD_APP_BASE64} | base64 --decode > /transcriber/gsc_creds.json

COPY . .
RUN npm install

RUN echo "GOOGLE_APPLICATION_CREDENTIALS=/transcriber/gsc_creds.json" >> .env

# ADD AWS CREDENTIALS FILE
RUN mkdir ~/.aws
RUN echo ${AWS_KEYS_FILE_BASE64} | base64 --decode > ~/.aws/credentials

CMD ["npm", "run", "docker:dev"]