FROM hassanamin994/node_ffmpeg
WORKDIR /transcriber-service

COPY . .
RUN npm install

# ADD AWS CREDENTIALS FILE
RUN mkdir ~/.aws
RUN echo ${AWS_KEYS_FILE_BASE64} | base64 --decode > ~/.aws/credentials

CMD ["npm", "run", "docker:dev"]